language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - CXX="g++-4.8" TRAVIS_NODE_VERSION="6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - xvfb

cache:
  apt: true
  directories:
    - node_modules
    - $HOME/.composer/cache

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - composer install --prefer-dist

before_script:
  - MINK_PHP_BIN=~/.phpenv/versions/5.6/bin/php vendor/bin/mink-test-server > /dev/null 2>&1 &

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
