language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm-3.18

env:
  - CXX="g++-4.8" TRAVIS_NODE_VERSION="6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - xvfb

cache:
  apt: true
  directories:
    - node_modules
    - $HOME/.composer/cache

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - composer install --prefer-dist

before_script:
  - ~/.phpenv/versions/5.6/bin/php -S "localhost:8002" -t "vendor/mink/driver-testsuite/web-fixtures" > /dev/null 2>&1 &

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
  - php -r "readfile('https://gist.githubusercontent.com/uuf6429/b6df80e2aedd80dd9e5af4cf5575795a/raw/264eaa37db2e56c180977100335f489a6b4d2209/loghighlight.php');" | php -- tmp/output.log
